server:
  port: 18080
nacos:
  config:
    server-addr: 127.0.0.1:8848
spring:
  application:
    name: dubbo-nacos-gateway
sentinel:
  config:
    nacos:
      serveraddr: 127.0.0.1:8848
      dataid: dubbo-nacos-gateway-rules
      groupid: SENTINEL_GROUP
route:
  config:
    nacos:
      serveraddr: 127.0.0.1:8848
      dataid: routes-config
      groupid: GATEWAY_GROUP